/********************
*FIRST WORKSHOP C
*Name: Julian Cardenas
*Subject: Parallel and Distributed Computing (II)
*Date: 16/08/2022
********************/


GCC = gcc
FLAGS = -ansi -pedantic -Wall -std=c99
D_POSIX_C_SOURSE=199309L
MATHFLAG = -lm

PROGS = main

all: $(PROGS)

main:
	gcc main.c -lm
	#$(GCC) $(FLAGS) -c proyectoFuncional_lib.c
	#$(GCC) $(FLAGS) -o $@ $@.o Taller1_lib.o $(MATHFLAG)
	#$(GCC) $(FLAGS) -o main main.c -lm
clean:
	$(RM) *.o $(PROGRS)
